logging:
  level.root: info
  config: classpath:logback-spring.xml
  file:
#    保存到项目目录下
#    path: ${user.dir}/logs/zephyr
#    保存到用户目录下
    path: ${user.home}/logs/zephyr

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: order-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:192.168.199.191}:${MYSQL_PORT:3306}/${MYSQL_DATABASES:sap-drp-uat}?useUnicode=true&characterEncoding=UTF8&useSsl=false
    username: ${MYSQL_USERNAME:sap}
    password: ${MYSQL_PASSWORD:sap@#321}
    type: com.zaxxer.hikari.HikariDataSource
    # Hikari 连接池配置
    # 最小空闲连接数量
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: >
    xyz.szy.zephyr.core.server.model

terminus:
  rocketmq:
    nameServerAddress: ${ROCKETMQ_NAMESRV_HOST:10.99.242.43}:${ROCKETMQ_NAMESRV_PORT:9876}
    producerGroup: ${MQ_GROUP:zephyr-producer}

dynamicDataSource:
  provider: ${DYNAMIC_DATASOURCE_PROVIDER:io.jjy.platform.common.datasource.provider.ConfigurableDataSourceProvider}
  groupKey: ${DYNAMIC_DATASOURCE_GROUPKEY:zephyr}

dubbo:
  application:
    name: core-center
    qosEnable: true
    qosPort: 22223
    qosAcceptForeignIp: false
  protocol:
    name: dubbo
    port: 26883
    accesslog: true
  provider:
    scan-packages: >
      xyz.szy.zephyr.core.api.service
    version: 2.6.2
  registry:
    id: core-server
    address: zookeeper://${ZOOKEEPER_HOST:10.99.196.156}:${ZOOKEEPER_PORT:2181}
  consumer:
    check: false
    timeout: 6000

#elastic:
#  job:
#    zk:
#      serverLists: ${ZOOKEEPER_HOST:10.99.196.156}:${ZOOKEEPER_PORT:2181}
#      namespace: test123fgh
#
#    JobName:
#      cron: 0/5 * * * * ?
#      overwrite: true
#      failover: true
#      misfire: true
#      shardingTotalCount: 3
#      shardingItemParameters: 0=3503,1=3526,2=1017