logging:
  level.root: info
  config: classpath:logback-spring.xml
  file:
    #    保存到项目目录下
    #    path: ${user.dir}/logs/zephyr
    #    保存到用户目录下
    path: ${user.home}/logs/zephyr

spring:
  application:
    name: zephyr-admin-starter

server:
  context-path: /
  port: 8082

security:
  basic:
    enabled: false

swagger:
  enable: true
  title: "ZEPHYR_CORE_API"
  group-name: "ZEPHYR"
  version: "1.0-SNAPSHOT"

dubbo:
  application:
    name: zephyr-core-dubbo
  registry:
    id: core-admin
    address: zookeeper://${ZOOKEEPER_HOST:10.99.196.156}:${ZOOKEEPER_PORT:2181}
  provider:
    retries: 0
  consumer:
    check: false
    timeout: 6000
  protocol:
    name: dubbo
    port: 26880